### ISSUE TITLE
Latest Version Tag is not read from GIT

### ISSUE THREAD

**Issue by psud** [datalbry/gradle-plugin-semver#8]
I am using the semver plugin for a library and have the issue that the last version is not correctly detected from the git tags.

In the GIT project there are the following tags (I also tried it without the v prefix)
- v0.1.0
- v0.2.0
 (I also tried "0.1.0" with the same result). When 

The versions generated by the plugin always are `v0.1.0-XXX` versions thus leading me to believe that the tag is not read and the plugin falls back to the default.

Plugin Configuration (version 0.2.2):
```
semver {
    version("alpha", "alpha.{COMMIT_TIMESTAMP}")
    version("beta", "beta.{COMMIT_TIMESTAMP}")
}
```

**Comment by Lacritz** [comment]
has been fixed in `v0.4.1`
